<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Prism.DryIoc" />

    <PackageReference Include="DevExpress.Wpf.Scheduling" />
    <PackageReference Include="DevExpress.Document.Processor" />
    <PackageReference Include="DevExpress.Drawing.Skia" />
    <PackageReference Include="DevExpress.RichEdit.Export" />
    <PackageReference Include="DevExpress.Wpf.Accordion" />
    <PackageReference Include="DevExpress.Wpf.Carousel" />
    <PackageReference Include="DevExpress.Wpf.Charts" />
    <PackageReference Include="DevExpress.Wpf.Core.Extensions" />
    <PackageReference Include="DevExpress.Wpf.Diagram" />
    <PackageReference Include="DevExpress.Wpf.Dialogs" />
    <PackageReference Include="DevExpress.Wpf.Docking" />
    <PackageReference Include="DevExpress.Wpf.DocumentViewer.Core" />
    <PackageReference Include="DevExpress.Wpf.ExpressionEditor" />
    <PackageReference Include="DevExpress.Wpf.Gauges" />
    <PackageReference Include="DevExpress.Wpf.Grid" />
    <PackageReference Include="DevExpress.Wpf.LayoutControl" />
    <PackageReference Include="DevExpress.Wpf.NavBar" />
    <PackageReference Include="DevExpress.Wpf.PdfViewer" />
    <PackageReference Include="DevExpress.Wpf.PivotGrid" />
    <PackageReference Include="DevExpress.Wpf.Printing" />
    <PackageReference Include="DevExpress.Wpf.PrismAdapters" />
    <PackageReference Include="DevExpress.Wpf.PropertyGrid" />
    <PackageReference Include="DevExpress.Wpf.Ribbon" />
    <PackageReference Include="DevExpress.Wpf.RichEdit" />
    <PackageReference Include="DevExpress.Wpf.SchedulingReporting" />
    <PackageReference Include="DevExpress.Wpf.SpellChecker" />
    <PackageReference Include="DevExpress.Wpf.Spreadsheet" />
    <PackageReference Include="DevExpress.Wpf.TypedStyles" />
    <PackageReference Include="DevExpress.Mvvm" />
    <PackageReference Include="DevExpress.Mvvm.CodeGenerators" />
    <PackageReference Include="DevExpress.Wpf.ThemesLW" />

    <!-- DevExpress transitive packages -->
    <PackageReference Include="DevExpress.Data" />
    <PackageReference Include="DevExpress.Data.Desktop" />
    <PackageReference Include="DevExpress.Images" />
    <PackageReference Include="DevExpress.Wpf.Controls" />
    <PackageReference Include="DevExpress.Wpf.Core" />
    <PackageReference Include="DevExpress.Wpf.Themes.Win11Light" />
 
  </ItemGroup>
  </Project>
