<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <EnableNUnitRunner>true</EnableNUnitRunner>
    <OutputType>Exe</OutputType>
    <TestingPlatformDotnetTestSupport>true</TestingPlatformDotnetTestSupport>
  </PropertyGroup>

  <ItemGroup>
    <Constant Include="BuildInfo.ApplicationPath" Value="$(ArtifactsPath)bin\ClinicManager.Win\debug_win-x64\ClinicMgr.exe" />
  </ItemGroup>


  <ItemGroup>
    <PackageReference Include="ThisAssembly.Constants" />
    <PackageReference Include="Shouldly" />
    <PackageReference Include="NUnit" />
    <PackageReference Include="NUnit.Analyzers">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="NUnit3TestAdapter" />
    <PackageReference Include="Microsoft.Testing.Extensions.CodeCoverage" />
    <PackageReference Include="FlaUI.Core.Signed" />
    <PackageReference Include="FlaUI.TestUtilities" />
    <PackageReference Include="FlaUI.UIA3.Signed" />
</ItemGroup>

  <ItemGroup>
  
  </ItemGroup>

</Project>
